---

# Push the containers
- name: "{{ ansible_aws_repo_op }} on {{ ansible_aws_image }}:{{ ansible_aws_tag }}"
  include: roles/ansible_aws/tasks/ansible_aws_repo_ops.yml  # Fully qualified, 'cos it might be invoked from elsewhere
  vars:
    ansible_aws_repo_op: push
    ansible_aws_image: "{{ ecr_item.image_name }}"
    ansible_aws_tag: "{{ ecr_item.image_tag }}"
  with_items: "{{ ansible_aws_items| default([]) }}"
  loop_control:
    loop_var: ecr_item

