---

- set_fact:
    ansible_aws_subtype_to_private_ip_dict: "{{ ansible_aws_subtype_to_private_ip_dict | default({}) | combine( { item.0 : item.1 } ) }}"
  with_together:
    - "{{ gi_result.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.ansible_aws_server_subtype')|list }}"
    - "{{ gi_result.instances|selectattr('state', 'equalto', 'running')|map(attribute='private_ip_address')|list }}"

- set_fact:
    ansible_aws_private_ip_to_subtype_dict: "{{ ansible_aws_private_ip_to_subtype_dict | default({}) | combine( { item.1 : item.0 } ) }}"
  with_together:
    - "{{ gi_result.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.ansible_aws_server_subtype')|list }}"
    - "{{ gi_result.instances|selectattr('state', 'equalto', 'running')|map(attribute='private_ip_address')|list }}"
