---

# Pull the containers
- name: "{{ aws_repo_op }} on {{ aws_image }}:{{ aws_tag }}"
  include: roles/ansible_aws/tasks/aws_repo_ops.yml   # Fully qualified, 'cos it might be invoked from elsewhere
  vars:
    aws_repo_op: pull
    aws_image: "{{ aws_image_name }}"
    aws_tag: "{{ aws_image_tag }}"

